language: node_js
node_js:
  - '10'
install:
  - yarn
script:
  - yarn global add @tarojs/cli
  - yarn build:h5
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  local_dir: dist
  on:
    branch: master
